# This file contains values from Cookiecutter

default_context:
  project_name: "binance-autotrader"
  project_description: "This project allowes users to trade crypto currencies on Binance.us using AI."
  organization: "binance-autotrader"
  license: "BSD-3"
  minimal_python_version: 3.9
  github_name: "binance_autotrader"
  email: "curt.m.k.wheeler@icloud.con"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
